### ISSUE TITLE
Works with Gencove data?

### ISSUE THREAD

**Issue by dbaranger** [arvkevi/openhumansimputer#109]
In the OpenHumans page for the project it says that Imputer works with Gencove data, but in the dashboard Gencove doesn't appear as a connected data source. Is Imputer compatible with data from Gencove?

**Comment by arvkevi** [comment]
Hi @dbaranger thanks for reporting the issue. I thought Gencove connections should be displayed on the dashboard. Would you mind sending me your Project Member ID, which you can find on the [activity page](https://www.openhumans.org/activity/imputer/). This way, I can debug why your file is not being displayed.

**Comment by dbaranger** [comment]
For sure, it's 69412477. Thanks!

**Comment by arvkevi** [comment]
Hi @dbaranger it's as I thought, the Gencove file that I see uploaded to your profile is a `.bam`. Imputer will only work with `.vcf` files. Can you try uploading a `.vcf` from Gencove?

Btw, I recognize your name and/or picture from the crowdAI height prediction challenge. I competed and like most, just tried a multi-layer perceptron neural network after doing PCA 🤣  

I read both of your posts (years? ago) discussing the winning solution, really interesting reads, and great work!

**Comment by dbaranger** [comment]
Awesome, thanks! Since I was an early user of Gencove it only returned my .bam. I had to de-authorize and then re-join for it to connect my .vcf too. 

Oh wow, open source genetics is a small world! And thank you! 😃

**Comment by arvkevi** [comment]
Glad to hear it, I'm going to close this thread then if that's OK?
