### ISSUE TITLE
Imputation not completed after estimated time

### ISSUE THREAD

**Issue by dbaranger** [arvkevi/openhumansimputer#110]
Hi again! 
Project Member ID: 69412477
My imputed file has not been returned, it has been a couple days, and the dashboard says I'm the only person in the queue. Is this another instance of a too-large file?

Source    file name                                      Data source id
Gencove | merged-312685483077.vcf.gz | 8946249

Thanks!

**Comment by arvkevi** [comment]
Hi @dbaranger thanks for the heads up, it seems like my logging app only sends me alert emails *sometimes*... sorry about that. I just re-launched the pipeline manually and will keep an eye on it tonight. It looks like the `.vcf` file had >28 million variants, which might be pushing the limits of the server's memory.

**Comment by arvkevi** [comment]
I've been watching Imputer for the last half-hour or so, and it's not even finished converting to plink yet. My guess is that this file will be too large to process on the server setup we currently have.
This happened to one or two other members and I tried Imputer locally on my 16Gb MacBook pro (w/ permission) and these still wouldn't fit into memory. 

Maybe I could check filesize before imputation and warn if too large and also alert members when their pipeline fails. (Although, I am *supposed* to be getting alerts via sentry!)

**Comment by arvkevi** [comment]
Update:
Imputer ran out of memory trying to process the file. Imputer splits imputation by chromosome and runs two in parallel. I'm trying now in serial to see if that will be enough memory.

At least my alerts are working again:
<img width="1121" alt="Screen Shot 2019-10-19 at 6 25 37 AM" src="https://user-images.githubusercontent.com/9151717/67143437-6c90d700-f239-11e9-8aee-ee8f4648b278.png">

**Comment by arvkevi** [comment]
Hi @dbaranger you should have received your results. These only contain autosomes.

**Comment by dbaranger** [comment]
Hey! I got it, thanks again for your help and this awesome service!!
