### ISSUE TITLE
Send alert to member when imputation complete

### ISSUE THREAD

**Issue by arvkevi** [arvkevi/openhumansimputer#19]
@gedankenstuecke is it possible to message an Open Humans member directly?

**Comment by gedankenstuecke** [comment]
Yes, you can send a message trough Open Humans with the API. If you're using the `ohapi` package this can be done with `ohapi.api.message`, the [docs](http://open-humans-api.readthedocs.io/en/latest/ohapi.html#module-ohapi.api) have all the parameters needed, but basically it's just providing the project_member_id, their access_token & a subject/body 👍
