### ISSUE TITLE
Imputation queue halted

### ISSUE THREAD

**Issue by alexgieg** [arvkevi/openhumansimputer#223]
Hello! I submitted a file for imputation via OpenHumans on Jan. 22, 2022:

![image](https://user-images.githubusercontent.com/1074619/151665557-4ff559e4-5b92-4967-8823-3868e4edc191.png)

At the time the Imputation Dashboard said there were 25 members in front of me, and for me to wait 4 hours times that number, or 100 hours (4 days and 4 hours). It's been a week, so I checked and the queue remains stuck at 25 members in front of me:

![image](https://user-images.githubusercontent.com/1074619/151665456-b4ab42b6-e60f-4aa1-aa2d-4a04f7835177.png)

My project member ID on OpenHumans, as shown above, is 90212989. My data source ID on Imputer is 43417922.

I hope this helps! Thanks!

**Comment by arvkevi** [comment]
Hi @alexgieg, thank you for raising this issue. There was a silent bug that I didn't catch a couple of months ago. I cleaned up the queue, you should be able to access your results now.

**Comment by alexgieg** [comment]
Thank you very much!
