### ISSUE TITLE
long-running celery tasks cause duplicate tasks to be submitted to queue

### ISSUE THREAD

**Issue by arvkevi** [arvkevi/openhumansimputer#38]
Tasks are not being `acknowledged` by the celery worker while waiting for other long-running tasks to complete, so they trip the default `visibility_timeout` and are autmatically resubmitted :cry:. 

What is the difference between setting `visibility_timeout` in [`result_backend_transport-options`](http://docs.celeryproject.org/en/latest/userguide/configuration.html#result-backend-transport-options) vs setting it in [`broker_transport_options`](http://docs.celeryproject.org/en/latest/getting-started/brokers/redis.html#visibility-timeout)

**Chromosome 1 alone takes ~100 mins to impute. After 60 mins, chroms 2-22 all have their tasks duplicated. Subsequently, when chrom2 is running, it takes ~90 mins to impute, again after 60 min, chroms 3-22 will duplicate their tasks, and so on, until whichever chromosome takes <60mins to impute is reached.** @gedankenstuecke I think this has to be what's causing the duplicate tasks. It's been [documented](https://github.com/celery/celery/issues/2481#issuecomment-93710273) for long-running taks. This would also explain why when I run with `TEST_CHROMS=true` (only chr21 & chr22), I don't see this behaviour, because each takes ~7min to impute.
@beaugunderson have you experienced this behaviour with celery before?

[pipeline source code](https://github.com/arvkevi/openhumansimputer/blob/0ea5e73adef76a30b9c29356234f3f73028331a7/imputer/tasks.py#L305-L315)

Finally, maybe switch to `rabbitmq` [it has no visibility timeout](https://github.com/celery/django-celery/issues/215#issuecomment-163855750)

**Comment by beaugunderson** [comment]
@arvkevi i have not, but i also have not used celery with tasks longer than 30 minutes or so; and for what it's worth any time i've used celery i've used rabbitmq as the broker, if memory serves :)

**Comment by arvkevi** [comment]
Thanks for taking a look, sounds like it's easiest to just make the switch to rabbitmq.
