### ISSUE TITLE
Store input vcf url

### ISSUE THREAD

**Issue by arvkevi** [arvkevi/openhumansimputer#78]
Will help for pipeline restarts

**Comment by gedankenstuecke** [comment]
I'd suggest not storing the URL but the file ID (or the data source). The URLs returned from the open humans API are valid only for a certain time window, so they might have expired by the time the pipeline restarts. The file ID should not change (unless people replace the file). Even safer would be using just the data source and then grab a new `exchange_member` object that has all the files and pick the right one :-) 

Cheers,
Bastian

**Comment by arvkevi** [comment]
fixed by #79
