### ISSUE TITLE
Imputation pipeline queue unchanged for >24 hours

### ISSUE THREAD

**Issue by katielorrie** [arvkevi/openhumansimputer#82]
For the last couple of days, my dashboard on Imputer has continued to say that there are 4 individuals ahead of me in the pipeline. Prior to this, the number had been decreasing as expected - one fewer person in queue approximately every 4 hours.

**Comment by arvkevi** [comment]
Hi @katielorrie thank you for checking out Imputer and for opening the issue. There were, indeed, 4 samples which failed last week. If you can send me a message via Open Humans then I’ll be able to see your member ID number and I can tell you exactly what happened.

My guess is that the input vcf did not have any chromosome X variants which currently  causes Imputer to fail 😞... 

I’m traveling for a few days, but finishing the failed samples and fixing the chrX bug is top priority when I return next week. Sorry for the inconvenience.

**Comment by katielorrie** [comment]
Hi @arvkevi - thanks for the quick reply and additional information (and for the impetus to get started on GitHub- as previously I've downloaded others' code but not taken the time to make my own). I just sent you a message via Open Humans. No rush-- enjoy your travel!

**Comment by arvkevi** [comment]
Imputer now handles a variable number of chromosomes (fixed by #84 ), however, in this case, the input file ended u being too large to be processed on the Imputer server.

**Comment by arvkevi** [comment]
looks like you should have results @katielorrie 😄

**Comment by katielorrie** [comment]
@arvkevi yes, thanks! as an aside, if I have more than one dataset uploaded to one of the data streams imputer connects to is there a way to choose which dataset is used for imputation?

**Comment by arvkevi** [comment]
Great @katielorrie and good question, imputer currently uploads the first file (whichever one that may be...). This would be worth opening as a new issue I think. I'm ashamed to admit that I wasn't aware there could be more than one file per data source 😞

**Comment by katielorrie** [comment]
I figured that it must use the first one. Which means that I have the imputed data for a family member but not mine yet ;) in that case, I'll open a new issue.

**Comment by gedankenstuecke** [comment]
Hey, I wanted to chime in here as a member of the Open Humans team! 

You should not upload or import files from other folks into your personal Open Humans account, as this becomes problematic once you start sharing this data with third parties. 

I understand that your family members might have consented to you uploading the data to Open Humans and to you making decisions about how to share that data with third parties. But from the further sharing perspective it's not ideal if it's all mixed into a single account as the idea is that all the data associated with a single Open Humans member belongs to a single individual. I'd be happy to chat more about that, also via email at bastian@openhumans.org

**Comment by madprime** [comment]
This is in our Data Use Policy:
"Unless otherwise allowed via written agreement with Open Humans, an account must represent an individual – your personal data, or someone for whom you are a legal guardian."

And it is prominent in the account creation page. 
![image](https://user-images.githubusercontent.com/82631/56179428-8fa4aa80-5fba-11e9-8e39-e99c89357553.png)

**Comment by katielorrie** [comment]
@gedankenstuecke @madprime The primary reason I uploaded the family member's data (and yes it was with their express consent and awareness of exactly how it was being used) was to use with the lineage tool, which allows you to compare shared lineage. I'm a bit confused how that can be an approved openhumans tool if you are not expecting individuals to upload other's data too. 
I do not plan on publicly sharing anyone's info but my own. 

The reason that the family member's data was processed on imputer in the first place was a mistake. I was unable to select which file was used when imputer processed it and it just so happens that the family member's 23andme was uploaded first on that data source-- because my data was originally from another source-- and I only uploaded to the 23andme upload source after my original source was too large to work with imputer. I didn't realize until after I submitted the imputer file the second time that it was running on the family member's file and not my own. 

I don't want to be in violation of any of the rules of the organization, so I'm happy to delete the family member's data if need be. I do think that maybe given lineage's feature to make comparisons between relatives, you might want to make it more clear if we should not/cannot upload relatives' info via one of the other toolboxes to facilitate exploration on lineage tool. Thanks for your feedback and for all that you do to promote open data sharing and research.

**Comment by gedankenstuecke** [comment]
@katielorrie no problem, I assumed something along the lines! The *lineage* tool offers a way to upload additional people which don't have their data in Open Humans to get around those limitations (i.e. that an Open Humans account only represents a single member).

If you go to https://lineage.app/individuals/ you can upload additional data which will only be stored in Lineage. You can then compare those data with that of your relatives & friends. 

And it would be great if you could remove the additional files of your family members, just in case you want to share data with other projects on Open Humans. I hope that helps!

**Comment by katielorrie** [comment]
@gedankenstuecke gotcha! I think that when I read about lineage tool I must've just assumed that I should upload the other files via the 23andme upload, and it wasn't until using the lineage tool that I saw the separate place where you can upload other individual's data. I also didn't realize that the upload you do there is separate/apart from the openhumans account upload. I will correct my openhumans account, so that it only has my data. 

As a bonus, that will likely fix my problem of being unable to select the appropriate file for use in imputer ;) So @arvkevi maybe the new issue I opened doesn't need to be an issue after all. I suppose there could be individuals who get themselves sequenced more than once from the same data source-- as 23andme and AncestryDNA have updated the SNPs reported on etc. over the years- but may not be worth your time to plan for that rare occasion.

**Comment by gedankenstuecke** [comment]
Thanks so much @katielorrie! 

And I agree, people having done 23andMe more than once are probably a rare case, though it would be nice to plan for that nevertheless, but it's not super high priority (I am in fact one of the people who have done 23andMe twice :joy:)
