### ISSUE TITLE
option to chose which file from data source is imputed

### ISSUE THREAD

**Issue by katielorrie** [arvkevi/openhumansimputer#88]
Currently, when you select a data source to use with imputer, you are unable to select which file uploaded to that data source should be processed. As some data sources such as 23andme upload allow you to upload multiple files, it would be great to add this feature.

**Comment by arvkevi** [comment]
@katielorrie what do you think of the new Dashboard?

**Comment by katielorrie** [comment]
@arvkevi looks great! It's nice how you can now see the names of the connected files in addition to which connected data stream they are coming from and also you can see if it has been previously imputed and choose to re-impute.
