### ISSUE TITLE
failed or delayed impute?

### ISSUE THREAD

**Issue by brierjon** [arvkevi/openhumansimputer#98]
@arvkevi  The openimpute queue was 8 * 4 hours a week ago roughly when I initiated an Genome/Exome Upload impute (file type vcf.gz), today the queue says 5 more ahead and clicking impute button again since it doesn't indicated it is submitted by a change of display of the button results in "Oops! We checked, you already have an imputation job running. Please wait for that to finish before relaunching.".   Opening issue on Github as instructions state. :)

Has imputing been slow, delayed, or did it choked on a file/impute task?

**Comment by arvkevi** [comment]
Hi @brierjon 👋  thanks so much for checking out Imputer and taking the time to report the issue.

A quick update on the current status of Imputer: One sample was stuck (I need better exception handling it appears), this sample is back processing now. There are three samples which were too large to be processed on the server. I think I emailed these members each individually, so if you didn't get an OH message from me, it's likely not your sample. Finally, one sample was a multi-sample `.vcf`, of whom, I think I messaged this member as well.

A few takeaways for me:
1. Double check that failed pipelines are sent to the Sentry logging so I get promptly alerted.
2. After pipelines fail, reset their status in the database so they don't appear "in progress".
3. Check if OH has a message tracking history somewhere? Via the API maybe, so I can keep track of my messages.

**Comment by brierjon** [comment]
Thanks for the update, haven't seen any message. Will give it some time and see where we are in a few days. :)

**Comment by arvkevi** [comment]
Hi, @brierjon I've gone through (from what I can tell) all outstanding members in the pipeline and messaged each of them. There is currently one member in processing (78055078). 

If any of the following are True then I think I missed something we should re-open the issue.
You:
1. did NOT receive a message from me.
2. are not member 78055078.
3. have NOT received results this week.

Thank you!

**Comment by brierjon** [comment]
@arvkevi  I did get an email today & replied to discuss the failed to compute - too large issue. We can keep this closed and discuss via email.
